// Alert action types
export const SET_ALERT_MESSAGE = "SET_ALERT_MESSAGE";

// Authentication action types
export const SET_IS_AUTHORIZED = "SET_IS_AUTHORIZED";
export const SET_IS_SERVER_DOWN = "SET_IS_SERVER_DOWN";

// File Viewer
export const SET_FILE_VIEWER_TEXT = "SET_FILE_VIEWER_TEXT";
export const SET_SECTIONS = "SET_SECTIONS";
export const SET_SENTENCES = "SET_SENTENCES";
export const SET_TOKENS = "SET_TOKENS";
export const SET_ENTITIES = "SET_ENTITIES";
export const SET_SPACY_LOADING = "SET_SPACY_LOADING";
export const RESET_ANNOTATIONS = "RESET_ANNOTATIONS";
export const SET_ANNOTATION_FOCUS = "SET_ANNOTATION_FOCUS";
export const SET_ANNOTATIONS = "SET_ANNOTATIONS";
export const SET_TAG_TEMPLATES = "SET_TAG_TEMPLATES";
export const SET_FILE_REFERENCE = "SET_FILE_REFERENCE";
export const SET_ALTERNATING_COLORS = "SET_ALTERNATING_COLORS";
export const SET_LINKED_LIST_ADD = "SET_LINKED_LIST_ADD";
export const SET_INTERVAL_DIV_HEIGHT = "SET_INTERVAL_DIV_HEIGHT";
export const SET_INTERVAL_DIV_WIDTH = "SET_INTERVAL_DIV_WIDTH";
export const SET_ANNOTATIONS_TO_EDIT = "SET_ANNOTATIONS_TO_EDIT";
export const SET_SPACY_ACTIVE = "SET_SPACY_ACTIVE";
export const SET_SNAP_TO_WORD = "SET_SNAP_TO_WORD";
export const SET_SECTIONS_IN_USE = "SET_SECTIONS_IN_USE";
export const SET_ENTITIES_IN_USE = "SET_ENTITIES_IN_USE";
export const SET_ADDING_CUSTOM_TAG = "SET_ADDING_CUSTOM_TAG";
export const SET_SPANS_RENDERED = "SET_SPANS_RENDERED";
export const SET_TXT_LIST = "SET_TXT_LIST";
export const SET_JSON_LIST = "SET_JSON_LIST";
export const SET_ANNOTATIONS_LIST = "SET_ANNOTATIONS_LIST";
export const SET_FILE_INDEX = "SET_FILE_INDEX";

// Tag Management
export const SET_UPLOADED_TAGS = "SET_UPLOADED_TAGS";
export const DISABLE_TAG_BY_INDEX = "DISABLE_TAG_BY_INDEX";
export const ENABLE_TAG_BY_INDEX = "ENABLE_TAG_BY_INDEX";
export const ENABLE_ALL_TAGS = "ENABLE_ALL_TAGS";
export const DISABLE_ALL_TAGS = "DISABLE_ALL_TAGS";
export const SET_ADDING_TAGS = "SET_ADDING_TAGS";
export const SET_INITIAL_TAGS_ADDED = "SET_INITIAL_TAGS_ADDED";
