// Alert action types
export const SET_ALERT_MESSAGE = "SET_ALERT_MESSAGE";

// Authentication action types
export const SET_IS_AUTHORIZED = "SET_IS_AUTHORIZED";
export const SET_USER_ROLE = "SET_USER_ROLE";
export const SET_IS_SERVER_DOWN = "SET_IS_SERVER_DOWN";

// Cached code action types
export const APPEND_TO_CACHE = "APPEND_TO_CACHE";

// File Viewer
export const SET_FILE_VIEWER_TEXT = "SET_FILE_VIEWER_TEXT";
export const SET_SENTENCES = "SET_SENTENCES";
export const SET_TOKENS = "SET_TOKENS";
export const SET_ENTITIES = "SET_ENTITIES";
export const SET_SPACY_LOADING = "SET_SPACY_LOADING";
export const RESET_ANNOTATIONS = "RESET_ANNOTATIONS";
export const SET_ANNOTATION_FOCUS = "SET_ANNOTATION_FOCUS";
export const SET_ANNOTATIONS = "SET_ANNOTATIONS";
export const SET_TAG_TEMPLATES = "SET_TAG_TEMPLATES";
export const SET_LINKED_LIST_ADD = "SET_LINKED_LIST_ADD";
export const SET_INTERVAL_DIV_HEIGHT = "SET_INTERVAL_DIV_HEIGHT";
export const SET_INTERVAL_DIV_WIDTH = "SET_INTERVAL_DIV_WIDTH";
export const SET_ANNOTATIONS_TO_EDIT = "SET_ANNOTATIONS_TO_EDIT";
export const SET_SNAP_TO_WORD = "SET_SNAP_TO_WORD";
export const SET_ENTITIES_IN_USE = "SET_ENTITIES_IN_USE";
export const SET_ADDING_CUSTOM_TAG = "SET_ADDING_CUSTOM_TAG";
export const SET_SPANS_RENDERED = "SET_SPANS_RENDERED";
export const SET_TXT_LIST = "SET_TXT_LIST";
export const SET_JSON_LIST = "SET_JSON_LIST";
export const SET_ANNOTATIONS_LIST = "SET_ANNOTATIONS_LIST";
export const SET_FILE_INDEX = "SET_FILE_INDEX";
export const SET_SESSION_ID = "SET_SESSION_ID";
export const SET_CURRENT_ENTITIES = "SET_CURRENT_ENTITIES";
export const SET_CURRENT_SENTENCES = "SET_CURRENT_SENTENCES";
export const SET_VERSIONS = "SET_VERSIONS";
export const SET_VERSION_INDEX = "SET_VERSION_INDEX";
export const SET_SENTENCES_AVAILABLE = "SET_SENTENCES_AVAILABLE";
export const SET_MODIFYING_ANNOTATION = "SET_MODIFYING_ANNOTATION";

// Tag Management
export const SET_UPLOADED_TAGS = "SET_UPLOADED_TAGS";
export const DISABLE_TAG_BY_INDEX = "DISABLE_TAG_BY_INDEX";
export const ENABLE_TAG_BY_INDEX = "ENABLE_TAG_BY_INDEX";
export const ENABLE_ALL_TAGS = "ENABLE_ALL_TAGS";
export const DISABLE_ALL_TAGS = "DISABLE_ALL_TAGS";
export const SET_ADDING_TAGS = "SET_ADDING_TAGS";
export const SET_INITIAL_TAGS_ADDED = "SET_INITIAL_TAGS_ADDED";

// Tree
export const SET_SELECTED_CODE = "SET_SELECTED_CODE";
