// Alert action types
export const SET_ALERT_MESSAGE = "SET_ALERT_MESSAGE";

// Authentication action types
export const SET_IS_AUTHORIZED = "SET_IS_AUTHORIZED";
export const SET_IS_SERVER_DOWN = "SET_IS_SERVER_DOWN";

// File Viewer
export const SET_FILE_VIEWER_TEXT = "SET_FILE_VIEWER_TEXT";
export const SET_SECTIONS = "SET_SECTIONS";
export const SET_SENTENCES = "SET_SENTENCES";
export const SET_TOKENS = "SET_TOKENS";
export const SET_ENTITIES = "SET_ENTITIES";
export const SET_SPACY_LOADING = "SET_SPACY_LOADING";
export const RESET_ANNOTATIONS = "RESET_ANNOTATIONS";
export const SET_ANNOTATION_FOCUS = "SET_ANNOTATION_FOCUS";
export const SET_ANNOTATIONS = "SET_ANNOTATIONS";
export const SET_TAG_COLORS = "SET_TAG_COLORS";
export const SET_SECTION_LIST = "SET_SECTION_LIST";
export const SET_TAG = "SET_TAG";
export const SET_FILE_REFERENCE = "SET_FILE_REFERENCE";
export const SET_ALTERNATING_COLORS = "SET_ALTERNATING_COLORS";
export const SET_LINKED_LIST_ADD = "SET_LINKED_LIST_ADD";

// Tag Management
export const SET_UPLOADED_TAGS = "SET_UPLOADED_TAGS";
export const DISABLE_TAG_BY_INDEX = "DISABLE_TAG_BY_INDEX";
export const ENABLE_TAG_BY_INDEX = "ENABLE_TAG_BY_INDEX";
export const ENABLE_ALL_TAGS = "ENABLE_ALL_TAGS";
export const DISABLE_ALL_TAGS = "DISABLE_ALL_TAGS";
